# Generated by Django 6.0.1 on 2026-02-05 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0002_person_photo"),
        ("users", "0002_alter_customuser_managers_remove_customuser_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="person",
            field=models.OneToOneField(
                blank=True,
                help_text="Each user must be linked to a person",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user",
                to="persons.person",
            ),
        ),
    ]
