# Generated by Django 6.0.1 on 2026-03-11 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
        ("persons", "0013_alter_person_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                ("position_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name_long",
                    models.CharField(
                        help_text="Full position name (e.g. Fire Chief, Senior Firefighter)",
                        max_length=255,
                    ),
                ),
                (
                    "name_short",
                    models.CharField(
                        help_text="Short position name (e.g. Chief, FF)", max_length=64
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("expat", "Expat"),
                            ("local", "Local"),
                            ("any", "Any"),
                        ],
                        default="any",
                        help_text="Allowed staff type for this position",
                        max_length=5,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this position is active and selectable",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Company this position belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_positions",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "staff_positions",
                "ordering": ["name_long"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                ("shift_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "shift_no",
                    models.PositiveSmallIntegerField(
                        help_text="Sequential number inside pattern package: 1, 2, 3 ..."
                    ),
                ),
                (
                    "shift_number",
                    models.CharField(
                        help_text="Full shift code, generated from pattern code + shift_no, e.g. A1, A2, B1",
                        max_length=8,
                    ),
                ),
                (
                    "anchor_date",
                    models.DateField(
                        blank=True,
                        help_text="First day when this concrete shift starts its duty block.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this shift is active and selectable",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Company this shift belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_shifts",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "staff_shifts",
                "ordering": ["shift_type__code_letter", "shift_no"],
            },
        ),
        migrations.CreateModel(
            name="ShiftMembership",
            fields=[
                (
                    "shift_membership_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_memberships",
                        to="companies.company",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_memberships",
                        to="persons.person",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="staff.shift",
                    ),
                ),
            ],
            options={
                "db_table": "staff_shift_memberships",
                "ordering": ["-is_active", "-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftType",
            fields=[
                (
                    "shift_type_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "code_letter",
                    models.CharField(
                        help_text="Letter code of pattern, e.g. A, B, C", max_length=2
                    ),
                ),
                (
                    "shift_type_name",
                    models.CharField(
                        help_text="Long name for this shift type (e.g. Rotation 7/14)",
                        max_length=255,
                    ),
                ),
                (
                    "shift_type_short",
                    models.CharField(
                        help_text="Short pattern text, e.g. 7/14, 28/28, 2/2",
                        max_length=10,
                    ),
                ),
                (
                    "shift_days_on",
                    models.PositiveSmallIntegerField(
                        help_text="Number of consecutive work days"
                    ),
                ),
                (
                    "shift_days_off",
                    models.PositiveSmallIntegerField(
                        help_text="Number of consecutive off days after work block"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this shift type is active and selectable",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Company this shift type belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_shift_types",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "staff_shift_types",
                "ordering": ["code_letter", "shift_type_short"],
            },
        ),
        migrations.AddField(
            model_name="shift",
            name="shift_type",
            field=models.ForeignKey(
                help_text="Link to shift type (pattern)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shifts",
                to="staff.shifttype",
            ),
        ),
        migrations.CreateModel(
            name="StaffAbsence",
            fields=[
                ("absence_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "absence_type",
                    models.CharField(
                        choices=[
                            ("sick", "Sick leave"),
                            ("vac", "Vacation"),
                            ("off", "Day off"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=8,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_absences",
                        to="companies.company",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "db_table": "staff_absences",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffEmployment",
            fields=[
                (
                    "employment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("hired_on", models.DateField(blank=True, null=True)),
                ("terminated_on", models.DateField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Active employment (person is currently hired by this company).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_employments",
                        to="companies.company",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employments",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "db_table": "staff_employments",
                "ordering": ["-is_active", "company", "person"],
            },
        ),
        migrations.CreateModel(
            name="StaffingPlan",
            fields=[
                (
                    "staffing_plan_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "staffing_plan_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable staffing plan name",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this staffing plan belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staffing_plans",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "staff_staffing_plans",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffingPlanItem",
            fields=[
                (
                    "staffing_plan_item_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("position_qty", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staffing_plan_items",
                        to="staff.position",
                    ),
                ),
                (
                    "shift_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staffing_plan_items",
                        to="staff.shifttype",
                    ),
                ),
                (
                    "staffing_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="staff.staffingplan",
                    ),
                ),
            ],
            options={
                "db_table": "staff_staffing_plan_items",
                "ordering": [
                    "position__name_long",
                    "shift_type__code_letter",
                    "shift_type__shift_type_short",
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffingAssignment",
            fields=[
                (
                    "staffing_assignment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Redundant but useful for filtering and consistency checks.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staffing_assignments",
                        to="companies.company",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staffing_assignments",
                        to="persons.person",
                    ),
                ),
                (
                    "staffing_plan_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="staff.staffingplanitem",
                    ),
                ),
            ],
            options={
                "db_table": "staff_staffing_assignments",
                "ordering": ["-is_active", "-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="RosterOverride",
            fields=[
                ("override_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("day", models.DateField(db_index=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_overrides",
                        to="companies.company",
                    ),
                ),
                (
                    "replaced_person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: who is replaced (can be empty)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster_overrides_replaced",
                        to="persons.person",
                    ),
                ),
                (
                    "replacement_person",
                    models.ForeignKey(
                        help_text="Who works instead",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster_overrides_replacement",
                        to="persons.person",
                    ),
                ),
                (
                    "staffing_plan_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_overrides",
                        to="staff.staffingplanitem",
                    ),
                ),
            ],
            options={
                "db_table": "staff_roster_overrides",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("company", "name_long"),
                name="uq_staff_position_company_name_long",
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("company", "name_short"),
                name="uq_staff_position_company_name_short",
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("company", "person"),
                name="uq_shift_membership_company_person_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="shifttype",
            constraint=models.UniqueConstraint(
                fields=("company", "code_letter"),
                name="uq_staff_shift_type_company_code_letter",
            ),
        ),
        migrations.AddConstraint(
            model_name="shifttype",
            constraint=models.UniqueConstraint(
                fields=("company", "shift_type_short"),
                name="uq_staff_shift_type_company_short",
            ),
        ),
        migrations.AddConstraint(
            model_name="shifttype",
            constraint=models.UniqueConstraint(
                fields=("company", "shift_type_name"),
                name="uq_staff_shift_type_company_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="shifttype",
            constraint=models.UniqueConstraint(
                fields=("company", "shift_days_on", "shift_days_off"),
                name="uq_staff_shift_type_company_pattern",
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                fields=("company", "shift_type", "shift_no"),
                name="uq_staff_shift_company_type_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                fields=("company", "shift_number"), name="uq_staff_shift_company_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffabsence",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_to__gte", models.F("date_from"))),
                name="ck_absence_date_to_gte_from",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffemployment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("company", "person"),
                name="uq_staff_employment_company_person_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffemployment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("person",),
                name="uq_staff_employment_person_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffingplanitem",
            constraint=models.UniqueConstraint(
                fields=("staffing_plan", "position", "shift_type"),
                name="uq_staffing_plan_item_plan_position_shifttype",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffingassignment",
            constraint=models.UniqueConstraint(
                fields=("staffing_plan_item", "person"),
                name="uq_staffing_assignment_item_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="rosteroverride",
            constraint=models.UniqueConstraint(
                fields=("company", "day", "staffing_plan_item", "replacement_person"),
                name="uq_roster_override_company_day_item_person",
            ),
        ),
    ]
