# Generated by Django 6.0.1 on 2026-02-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                ("position_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name_long",
                    models.CharField(
                        help_text="Full position name (e.g. Firefighter Team Leader)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name_short",
                    models.CharField(
                        help_text="Short name or abbreviation (e.g. FTL)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EXPAT", "Expat"),
                            ("LOCAL", "Local"),
                            ("ANY", "Any"),
                        ],
                        db_index=True,
                        default="ANY",
                        help_text="Allowed staff type for this position",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "staff_positions",
                "ordering": ["name_long"],
            },
        ),
    ]
