# Generated by Django 6.0.1 on 2026-02-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this position is active and selectable"
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name_long",
            field=models.CharField(
                help_text="Full position name (e.g. Fire Chief, Senior Firefighter)",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name_short",
            field=models.CharField(
                help_text="Short position name (e.g. Chief, FF)",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="type",
            field=models.CharField(
                choices=[("expat", "Expat"), ("local", "Local"), ("any", "Any")],
                default="any",
                help_text="Allowed staff type for this position",
                max_length=5,
            ),
        ),
    ]
