# Generated by Django 6.0.1 on 2026-03-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffingplanitem",
            options={"ordering": ["position__name_long"]},
        ),
        migrations.RemoveConstraint(
            model_name="staffingplanitem",
            name="uq_staffing_plan_item_plan_position_shifttype",
        ),
        migrations.AddConstraint(
            model_name="staffingplanitem",
            constraint=models.UniqueConstraint(
                fields=("staffing_plan", "position"),
                name="uq_staffing_plan_item_plan_position",
            ),
        ),
        migrations.RemoveField(
            model_name="staffingplanitem",
            name="shift_type",
        ),
    ]
