# Generated by Django 6.0.1 on 2026-03-13 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
        ("staff", "0002_alter_staffingplanitem_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="staffemployment",
            name="uq_staff_employment_company_person_active",
        ),
        migrations.RemoveConstraint(
            model_name="staffemployment",
            name="uq_staff_employment_person_active",
        ),
        migrations.RemoveConstraint(
            model_name="staffingassignment",
            name="uq_staffing_assignment_item_person",
        ),
        migrations.AlterField(
            model_name="staffingassignment",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staffing_assignments",
                to="companies.company",
            ),
        ),
        migrations.DeleteModel(
            name="StaffEmployment",
        ),
    ]
