# Generated by Django 6.0.1 on 2026-02-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_position_is_active_alter_position_name_long_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                ("shift_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "work_days",
                    models.PositiveSmallIntegerField(
                        help_text="Number of consecutive work days"
                    ),
                ),
                (
                    "off_days",
                    models.PositiveSmallIntegerField(
                        help_text="Number of consecutive off days before next shift"
                    ),
                ),
                (
                    "shift_number",
                    models.CharField(
                        help_text="Manual code (2 chars): letters or digits, e.g. A1, 01, B2",
                        max_length=2,
                    ),
                ),
                (
                    "shift_type",
                    models.CharField(
                        help_text="Letters/digits code up to 8 chars, e.g. DAY, NIGHT, 24H, ROT14",
                        max_length=8,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this shift is active and selectable",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "staff_shifts",
                "ordering": ["shift_number", "shift_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shift_number", "shift_type"),
                        name="uq_staff_shift_number_type",
                    )
                ],
            },
        ),
    ]
