# Generated by Django 6.0.1 on 2026-03-14 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
        ("persons", "0013_alter_person_company"),
        (
            "staff",
            "0003_remove_staffemployment_uq_staff_employment_company_person_active_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="staffingplan",
            name="active_from",
            field=models.DateField(
                blank=True,
                help_text="Date from which this staffing plan becomes effective.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="staffingplan",
            name="active_to",
            field=models.DateField(
                blank=True,
                help_text="Date until which this staffing plan is effective.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staffabsence",
            name="absence_type",
            field=models.CharField(
                choices=[
                    ("sick", "Sick leave"),
                    ("annual_leave", "Annual paid leave"),
                    ("unpaid_leave", "Unpaid leave"),
                    ("absent_without_leave", "Absent without leave"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="ExtraWork",
            fields=[
                (
                    "extra_work_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("day", models.DateField(db_index=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_works",
                        to="companies.company",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extra_works",
                        to="persons.person",
                    ),
                ),
                (
                    "staffing_plan_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional slot/position for which extra work is performed.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_works",
                        to="staff.staffingplanitem",
                    ),
                ),
            ],
            options={
                "db_table": "staff_extra_works",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtraWorkDocument",
            fields=[
                (
                    "extra_work_document_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "document_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional document name shown in UI.",
                        max_length=100,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Supporting document for extra work.",
                        upload_to="staff/extra_work/documents/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extra_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="staff.extrawork",
                    ),
                ),
            ],
            options={
                "db_table": "staff_extra_work_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffAbsenceDocument",
            fields=[
                (
                    "absence_document_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "document_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional document name shown in UI.",
                        max_length=100,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Supporting document for absence.",
                        upload_to="staff/absences/documents/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "absence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="staff.staffabsence",
                    ),
                ),
            ],
            options={
                "db_table": "staff_absence_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TemporaryCover",
            fields=[
                (
                    "temporary_cover_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("day", models.DateField(db_index=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "absent_person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who is absent / replaced.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="temporary_covers_as_absent",
                        to="persons.person",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_covers",
                        to="companies.company",
                    ),
                ),
                (
                    "covering_person",
                    models.ForeignKey(
                        help_text="Person who covers the duty.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="temporary_covers_as_covering",
                        to="persons.person",
                    ),
                ),
                (
                    "staffing_plan_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_covers",
                        to="staff.staffingplanitem",
                    ),
                ),
            ],
            options={
                "db_table": "staff_temporary_covers",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemporaryCoverDocument",
            fields=[
                (
                    "temporary_cover_document_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "document_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional document name shown in UI.",
                        max_length=100,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Supporting document for temporary cover.",
                        upload_to="staff/temporary_covers/documents/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "temporary_cover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="staff.temporarycover",
                    ),
                ),
            ],
            options={
                "db_table": "staff_temporary_cover_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="extrawork",
            constraint=models.UniqueConstraint(
                fields=("company", "person", "day"),
                name="uq_extra_work_company_person_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="temporarycover",
            constraint=models.UniqueConstraint(
                fields=("company", "day", "staffing_plan_item", "covering_person"),
                name="uq_temp_cover_company_day_item_covering_person",
            ),
        ),
    ]
