# Generated by Django 6.0.1 on 2026-02-08 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_shift"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftType",
            fields=[
                (
                    "shift_type_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "shift_type_name",
                    models.CharField(
                        help_text="Long name for this shift type (e.g. Rotation 14/14, Night Shift)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "shift_type_short",
                    models.CharField(
                        help_text="Short code up to 10 chars (letters/digits/signs), e.g. 14/14, NGT, D1",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "shift_days_on",
                    models.PositiveSmallIntegerField(
                        help_text="Number of consecutive work days"
                    ),
                ),
                (
                    "shift_days_off",
                    models.PositiveSmallIntegerField(
                        help_text="Number of consecutive off days after the shift"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this shift type is active and selectable",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "staff_shift_types",
                "ordering": ["shift_type_short"],
            },
        ),
        migrations.AlterModelOptions(
            name="shift",
            options={"ordering": ["shift_number", "shift_type__shift_type_short"]},
        ),
        migrations.RemoveConstraint(
            model_name="shift",
            name="uq_staff_shift_number_type",
        ),
        migrations.AddConstraint(
            model_name="shifttype",
            constraint=models.UniqueConstraint(
                fields=("shift_days_on", "shift_days_off", "shift_type_short"),
                name="uq_shift_type_pattern_short",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="shift_type",
            field=models.ForeignKey(
                help_text="Link to shift type (pattern)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shifts",
                to="staff.shifttype",
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                fields=("shift_number", "shift_type"),
                name="uq_staff_shift_number_type_fk",
            ),
        ),
        migrations.RemoveField(
            model_name="shift",
            name="off_days",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="work_days",
        ),
    ]
