# Generated by Django 6.0.1 on 2026-02-08 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
        ("staff", "0004_shifttype_alter_shift_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffingPlan",
            fields=[
                (
                    "staffing_plan_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "staff_staffing_plans",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffingPlanItem",
            fields=[
                (
                    "staffing_plan_item_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("position_qty", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "staff_staffing_plan_items",
                "ordering": ["position__name_long", "shift_type__shift_type_short"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="shift",
            name="uq_staff_shift_number_type_fk",
        ),
        migrations.RemoveConstraint(
            model_name="shifttype",
            name="uq_shift_type_pattern_short",
        ),
        migrations.AddField(
            model_name="position",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company this position belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_positions",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company this shift belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_shifts",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="shifttype",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company this shift type belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_shift_types",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name_long",
            field=models.CharField(
                help_text="Full position name (e.g. Fire Chief, Senior Firefighter)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name_short",
            field=models.CharField(
                help_text="Short position name (e.g. Chief, FF)", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="shifttype",
            name="shift_type_name",
            field=models.CharField(
                help_text="Long name for this shift type (e.g. Rotation 14/14, Night Shift)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="shifttype",
            name="shift_type_short",
            field=models.CharField(
                help_text="Short code up to 10 chars (letters/digits/signs), e.g. 14/14, NGT, D1",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("company", "name_long"),
                name="uq_staff_position_company_name_long",
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("company", "name_short"),
                name="uq_staff_position_company_name_short",
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                fields=("company", "shift_number", "shift_type"),
                name="uq_staff_shift_company_number_type_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="shifttype",
            constraint=models.UniqueConstraint(
                fields=("company", "shift_type_short"),
                name="uq_staff_shift_type_company_short",
            ),
        ),
        migrations.AddConstraint(
            model_name="shifttype",
            constraint=models.UniqueConstraint(
                fields=("company", "shift_type_name"),
                name="uq_staff_shift_type_company_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="shifttype",
            constraint=models.UniqueConstraint(
                fields=(
                    "company",
                    "shift_days_on",
                    "shift_days_off",
                    "shift_type_short",
                ),
                name="uq_shift_type_pattern_short_company",
            ),
        ),
        migrations.AddField(
            model_name="staffingplan",
            name="company",
            field=models.ForeignKey(
                help_text="Company this staffing plan belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staffing_plans",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="staffingplanitem",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staffing_plan_items",
                to="staff.position",
            ),
        ),
        migrations.AddField(
            model_name="staffingplanitem",
            name="shift_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staffing_plan_items",
                to="staff.shifttype",
            ),
        ),
        migrations.AddField(
            model_name="staffingplanitem",
            name="staffing_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="staff.staffingplan",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffingplanitem",
            constraint=models.UniqueConstraint(
                fields=("staffing_plan", "position", "shift_type"),
                name="uq_staffing_plan_item_plan_position_shifttype",
            ),
        ),
    ]
