# Generated by Django 6.0.1 on 2026-03-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_staffingplan_active_from_staffingplan_active_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffingassignment",
            name="assigned_at",
            field=models.DateTimeField(),
        ),
    ]
