# Generated by Django 6.0.1 on 2026-03-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
        ("staff", "0005_alter_staffingassignment_assigned_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="extrawork",
            name="uq_extra_work_company_person_day",
        ),
        migrations.RemoveField(
            model_name="extraworkdocument",
            name="extra_work",
        ),
        migrations.RemoveField(
            model_name="staffabsencedocument",
            name="absence",
        ),
        migrations.RemoveConstraint(
            model_name="temporarycover",
            name="uq_temp_cover_company_day_item_covering_person",
        ),
        migrations.RemoveField(
            model_name="temporarycoverdocument",
            name="temporary_cover",
        ),
        migrations.AlterModelOptions(
            name="rosteroverride",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="shiftmembership",
            options={"ordering": ["-assigned_at"]},
        ),
        migrations.AlterModelOptions(
            name="staffabsence",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="staffingassignment",
            options={"ordering": ["-assigned_at"]},
        ),
        migrations.AddField(
            model_name="position",
            name="roster_code",
            field=models.CharField(
                blank=True,
                help_text="Two-letter roster code for this position, e.g. TL, CR, DO, ME, FF, MT.",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("company", "roster_code"),
                name="uq_staff_position_company_roster_code",
            ),
        ),
        migrations.RemoveField(
            model_name="extrawork",
            name="company",
        ),
        migrations.RemoveField(
            model_name="extrawork",
            name="person",
        ),
        migrations.RemoveField(
            model_name="extrawork",
            name="staffing_plan_item",
        ),
        migrations.DeleteModel(
            name="ExtraWorkDocument",
        ),
        migrations.DeleteModel(
            name="StaffAbsenceDocument",
        ),
        migrations.RemoveField(
            model_name="temporarycover",
            name="absent_person",
        ),
        migrations.RemoveField(
            model_name="temporarycover",
            name="company",
        ),
        migrations.RemoveField(
            model_name="temporarycover",
            name="covering_person",
        ),
        migrations.RemoveField(
            model_name="temporarycover",
            name="staffing_plan_item",
        ),
        migrations.DeleteModel(
            name="TemporaryCoverDocument",
        ),
        migrations.DeleteModel(
            name="ExtraWork",
        ),
        migrations.DeleteModel(
            name="TemporaryCover",
        ),
    ]
