# Generated by Django 6.0.1 on 2026-02-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
        ("persons", "0010_person_residency_status"),
        ("staff", "0005_staffingplan_staffingplanitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffEmployment",
            fields=[
                (
                    "employment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("hired_on", models.DateField(blank=True, null=True)),
                ("terminated_on", models.DateField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Active employment (person is currently hired by this company).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_employments",
                        to="companies.company",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employments",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "db_table": "staff_employments",
                "ordering": ["-is_active", "company", "person_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "person"),
                        name="uq_staff_employment_company_person",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffingAssignment",
            fields=[
                (
                    "staffing_assignment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Redundant but удобный фильтр и контроль консистентности.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staffing_assignments",
                        to="companies.company",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staffing_assignments",
                        to="persons.person",
                    ),
                ),
                (
                    "staffing_plan_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="staff.staffingplanitem",
                    ),
                ),
            ],
            options={
                "db_table": "staff_staffing_assignments",
                "ordering": ["-is_active", "-assigned_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staffing_plan_item", "person"),
                        name="uq_staffing_assignment_item_person",
                    )
                ],
            },
        ),
    ]
