# Generated by Django 6.0.1 on 2026-02-09

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0006_staffemployment_staffingassignment"),
    ]

    operations = [
        # FIX ordering: убираем несуществующее person_id
        migrations.AlterModelOptions(
            name="staffemployment",
            options={
                "db_table": "staff_employments",
                "ordering": ["-is_active", "company", "person"],
            },
        ),
        # replace old constraint uq_staff_employment_company_person
        migrations.RemoveConstraint(
            model_name="staffemployment",
            name="uq_staff_employment_company_person",
        ),
        migrations.AddConstraint(
            model_name="staffemployment",
            constraint=models.UniqueConstraint(
                fields=("company", "person"),
                condition=Q(is_active=True),
                name="uq_staff_employment_company_person_active",
            ),
        ),
    ]
