# Generated by Django 6.0.1 on 2026-03-25 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
        ("persons", "0013_alter_person_company"),
        ("staff", "0006_remove_extrawork_uq_extra_work_company_person_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraWork",
            fields=[
                (
                    "extra_work_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("day", models.DateField(db_index=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "staff_extra_works",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtraWorkDocument",
            fields=[
                (
                    "extra_work_document_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "document_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional document name shown in UI.",
                        max_length=100,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Supporting document for extra work.",
                        upload_to="staff/extra_work/documents/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "staff_extra_work_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffAbsenceDocument",
            fields=[
                (
                    "absence_document_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "document_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional document name shown in UI.",
                        max_length=100,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Supporting document for absence.",
                        upload_to="staff/absences/documents/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "staff_absence_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TemporaryCover",
            fields=[
                (
                    "temporary_cover_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("day", models.DateField(db_index=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "staff_temporary_covers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemporaryCoverDocument",
            fields=[
                (
                    "temporary_cover_document_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "document_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional document name shown in UI.",
                        max_length=100,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Supporting document for temporary cover.",
                        upload_to="staff/temporary_covers/documents/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "staff_temporary_cover_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="position",
            name="uq_staff_position_company_roster_code",
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                condition=models.Q(("roster_code__isnull", False)),
                fields=("company", "roster_code"),
                name="uq_staff_position_company_roster_code",
            ),
        ),
        migrations.AddField(
            model_name="extrawork",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_works",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="extrawork",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="extra_works",
                to="persons.person",
            ),
        ),
        migrations.AddField(
            model_name="extrawork",
            name="staffing_plan_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional slot/position for which extra work is performed.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_works",
                to="staff.staffingplanitem",
            ),
        ),
        migrations.AddField(
            model_name="extraworkdocument",
            name="extra_work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="staff.extrawork",
            ),
        ),
        migrations.AddField(
            model_name="staffabsencedocument",
            name="absence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="staff.staffabsence",
            ),
        ),
        migrations.AddField(
            model_name="temporarycover",
            name="absent_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Person who is absent / replaced.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="temporary_covers_as_absent",
                to="persons.person",
            ),
        ),
        migrations.AddField(
            model_name="temporarycover",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temporary_covers",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="temporarycover",
            name="covering_person",
            field=models.ForeignKey(
                help_text="Person who covers the duty.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="temporary_covers_as_covering",
                to="persons.person",
            ),
        ),
        migrations.AddField(
            model_name="temporarycover",
            name="staffing_plan_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temporary_covers",
                to="staff.staffingplanitem",
            ),
        ),
        migrations.AddField(
            model_name="temporarycoverdocument",
            name="temporary_cover",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="staff.temporarycover",
            ),
        ),
        migrations.AddConstraint(
            model_name="extrawork",
            constraint=models.UniqueConstraint(
                fields=("company", "person", "day"),
                name="uq_extra_work_company_person_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="temporarycover",
            constraint=models.UniqueConstraint(
                fields=("company", "day", "staffing_plan_item", "covering_person"),
                name="uq_temp_cover_company_day_item_covering_person",
            ),
        ),
    ]
