# Generated by Django 6.0.1 on 2026-02-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0007_fix_staff_employment_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffingplan",
            name="staffing_plan_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable staffing plan name",
                max_length=255,
            ),
        ),
    ]
