# Generated by Django 6.0.1 on 2026-03-25 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
        ("staff", "0007_extrawork_extraworkdocument_staffabsencedocument_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "leave_type_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "leave_code",
                    models.CharField(
                        help_text="Two-letter leave code, e.g. SL, AL, UL, OL, BT, UV.",
                        max_length=2,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Full leave type name.", max_length=100),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional explanation / note shown in UI.",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this leave type is active and selectable.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Company this leave type belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_leave_types",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "staff_leave_types",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "leave_code"),
                        name="uq_staff_leave_type_company_code",
                    ),
                    models.UniqueConstraint(
                        fields=("company", "name"),
                        name="uq_staff_leave_type_company_name",
                    ),
                ],
            },
        ),
    ]
