# Generated by Django 6.0.1 on 2026-03-25 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0008_leavetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffabsence",
            name="leave_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Structured leave / non-duty type from LeaveType directory.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="absences",
                to="staff.leavetype",
            ),
        ),
    ]
