# Generated by Django 6.0.1 on 2026-02-11 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
        ("persons", "0011_personidscan_scan_name"),
        ("staff", "0008_staffingplan_staffing_plan_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="shifttype",
            name="anchor_date",
            field=models.DateField(
                blank=True,
                help_text="Rotation anchor date (first day when shift #1 is on duty).",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RosterOverride",
            fields=[
                ("override_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("day", models.DateField(db_index=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_overrides",
                        to="companies.company",
                    ),
                ),
                (
                    "replaced_person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: who is replaced (can be empty)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster_overrides_replaced",
                        to="persons.person",
                    ),
                ),
                (
                    "replacement_person",
                    models.ForeignKey(
                        help_text="Who works instead",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster_overrides_replacement",
                        to="persons.person",
                    ),
                ),
                (
                    "staffing_plan_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_overrides",
                        to="staff.staffingplanitem",
                    ),
                ),
            ],
            options={
                "db_table": "staff_roster_overrides",
                "ordering": ["-is_active", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "company",
                            "day",
                            "staffing_plan_item",
                            "replacement_person",
                        ),
                        name="uq_roster_override_company_day_item_person",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShiftMembership",
            fields=[
                (
                    "shift_membership_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_memberships",
                        to="companies.company",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_memberships",
                        to="persons.person",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="staff.shift",
                    ),
                ),
            ],
            options={
                "db_table": "staff_shift_memberships",
                "ordering": ["-is_active", "-assigned_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("company", "person"),
                        name="uq_shift_membership_company_person_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffAbsence",
            fields=[
                ("absence_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "absence_type",
                    models.CharField(
                        choices=[
                            ("sick", "Sick leave"),
                            ("vac", "Vacation"),
                            ("off", "Day off"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=8,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_absences",
                        to="companies.company",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "db_table": "staff_absences",
                "ordering": ["-is_active", "-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("date_to__gte", models.F("date_from"))),
                        name="ck_absence_date_to_gte_from",
                    )
                ],
            },
        ),
    ]
