# Generated by Django 6.0.1 on 2026-03-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0009_staffabsence_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporarycover",
            name="leave_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave type for absent person on this day.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="temporary_covers",
                to="staff.leavetype",
            ),
        ),
    ]
