# Generated by Django 6.0.1 on 2026-03-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
        ("persons", "0013_alter_person_company"),
        ("staff", "0009_shifttype_anchor_date_rosteroverride_shiftmembership_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="staffemployment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("person",),
                name="uq_staff_employment_person_active",
            ),
        ),
    ]
