# Generated by Django 6.0.1 on 2026-03-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0010_temporarycover_leave_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffabsence",
            name="absence_type",
        ),
        migrations.AlterField(
            model_name="staffabsence",
            name="leave_type",
            field=models.ForeignKey(
                help_text="Structured leave / non-duty type from LeaveType directory.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="absences",
                to="staff.leavetype",
            ),
        ),
    ]
