# Generated by Django 6.0.1 on 2026-03-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0013_alter_person_company"),
        ("staff", "0011_remove_staffabsence_absence_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporarycover",
            name="absence",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave/absence that this cover is closing.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="temporary_covers",
                to="staff.staffabsence",
            ),
        ),
        migrations.AlterField(
            model_name="temporarycover",
            name="absent_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Temporary legacy field. Will be replaced by absence.person.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="temporary_covers_as_absent",
                to="persons.person",
            ),
        ),
        migrations.AlterField(
            model_name="temporarycover",
            name="leave_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Temporary legacy field. Will be replaced by absence.leave_type.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="temporary_covers",
                to="staff.leavetype",
            ),
        ),
    ]
