# Generated by Django 6.0.1 on 2026-03-26 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0012_temporarycover_absence_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temporarycover",
            name="absent_person",
        ),
        migrations.RemoveField(
            model_name="temporarycover",
            name="leave_type",
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="leave_code",
            field=models.CharField(help_text="Two-letter leave code.", max_length=2),
        ),
        migrations.AlterField(
            model_name="temporarycover",
            name="absence",
            field=models.ForeignKey(
                help_text="Leave/absence that this cover is closing.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="temporary_covers",
                to="staff.staffabsence",
            ),
        ),
    ]
