# Generated by Django 6.0.1 on 2026-03-27 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
        ("persons", "0013_alter_person_company"),
        ("staff", "0013_remove_temporarycover_absent_person_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="temporarycover",
            options={"ordering": ["-date_from", "-created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="temporarycover",
            name="uq_temp_cover_company_day_item_covering_person",
        ),
        migrations.AddField(
            model_name="temporarycover",
            name="date_from",
            field=models.DateField(
                db_index=True,
                default=datetime.date(2026, 3, 27),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="temporarycover",
            name="date_to",
            field=models.DateField(
                db_index=True,
                default=datetime.date(2026, 3, 27),
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="temporarycover",
            name="day",
        ),
        migrations.AddConstraint(
            model_name="temporarycover",
            constraint=models.UniqueConstraint(
                fields=(
                    "company",
                    "date_from",
                    "date_to",
                    "staffing_plan_item",
                    "covering_person",
                ),
                name="uq_temp_cover_company_period_item_covering_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="temporarycover",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_to__gte", models.F("date_from"))),
                name="ck_temp_cover_date_to_gte_from",
            ),
        ),
    ]