# Generated by Django 6.0.1 on 2026-04-01 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0014_alter_temporarycover_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extrawork",
            name="staffing_plan_item",
        ),
        migrations.AddField(
            model_name="extrawork",
            name="position",
            field=models.ForeignKey(
                blank=True,
                help_text="Position worked on this extra day. This is outside staffing plan slots.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="extra_works",
                to="staff.position",
            ),
        ),
    ]
