DATE_FORMAT = "d/m/Y"
SHORT_DATE_FORMAT = "d/m/Y"
DATETIME_FORMAT = "d/m/Y H:i"
SHORT_DATETIME_FORMAT = "d/m/Y H:i"

TIME_FORMAT = "H:i"
SHORT_TIME_FORMAT = "H:i"

YEAR_MONTH_FORMAT = "F Y"
MONTH_DAY_FORMAT = "d F"