events {}

http {
    types {
        text/css css;
        application/javascript js;
        application/json json;
        image/svg+xml svg;
        image/png png;
        image/jpeg jpg jpeg;
        image/gif gif;
        font/woff woff;
        font/woff2 woff2;
    }
    default_type application/octet-stream;

    upstream django {
        server frs_web:8000;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/dev.crt;
        ssl_certificate_key /etc/nginx/certs/dev.key;

        location /static/ {
            alias /staticfiles/;
        }

        location / {
            proxy_pass http://django;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}