# Generated by Django 6.0.1 on 2026-02-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="companies/logos/"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="name_short",
            field=models.CharField(
                db_index=True, default="tmp", max_length=10, unique=True
            ),
            preserve_default=False,
        ),
    ]
