# Generated by Django 6.0.1 on 2026-02-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="persons/photos/"),
        ),
    ]
