# Generated by Django 6.0.1 on 2026-02-06 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0002_person_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code3",
                    models.CharField(
                        db_index=True,
                        help_text="Three-letter country code (ISO-3 style)",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        db_index=True,
                        help_text="Short country name (one word or abbreviation)",
                        max_length=64,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Official full country name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "countries",
                "ordering": ["code3"],
            },
        ),
        migrations.CreateModel(
            name="IDType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Machine-readable code (e.g. passport, national_id)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable document type name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "id_types",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PersonID",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "issued_on",
                    models.DateField(
                        blank=True, help_text="Document issue date", null=True
                    ),
                ),
                (
                    "valid_till",
                    models.DateField(
                        blank=True,
                        help_text="Expiration date (NULL = unlimited or not applicable)",
                        null=True,
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        db_index=True,
                        help_text="Document number (letters and digits allowed)",
                        max_length=64,
                    ),
                ),
                (
                    "id_std_sequence",
                    models.CharField(
                        blank=True,
                        help_text="Machine-readable sequence (MRZ, barcode, etc.)",
                        max_length=256,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person_ids",
                        to="persons.idtype",
                    ),
                ),
                (
                    "issued_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_person_ids",
                        to="persons.country",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ids",
                        to="persons.person",
                    ),
                ),
            ],
            options={
                "db_table": "person_ids",
                "ordering": ["person", "id_type", "id_number"],
            },
        ),
        migrations.CreateModel(
            name="PersonIDScan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded document scan (PDF/JPEG/PNG)",
                        upload_to="persons/ids/scans/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="persons.personid",
                    ),
                ),
            ],
            options={
                "db_table": "person_id_scans",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="personid",
            constraint=models.UniqueConstraint(
                fields=("person", "id_type", "id_number"),
                name="uq_person_idtype_idnumber",
            ),
        ),
    ]
