# Generated by Django 6.0.1 on 2026-02-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0003_country_idtype_personid_personidscan_and_more"),
        ("persons", "0004_country_seed"),
    ]

    operations = []
