# Generated by Django 6.0.1 on 2026-02-06 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0005_merge_20260206_1247"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="persons_by_nationality",
                to="persons.country",
            ),
        ),
    ]
