# Generated by Django 6.0.1 on 2026-02-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0007_country_seed_full_iso3166"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"permissions": [("hr_manager", "Can access HR Persons pages")]},
        ),
    ]
