# Generated by Django 6.0.1 on 2026-02-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0008_alter_person_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"permissions": [("hr_manager", "Can manage HR (persons)")]},
        ),
    ]
