# Generated by Django 6.0.1 on 2026-02-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0009_alter_person_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="residency_status",
            field=models.CharField(
                choices=[("EXPAT", "Expat"), ("LOCAL", "Local")],
                db_index=True,
                default="LOCAL",
                max_length=5,
            ),
        ),
    ]
