# Generated by Django 6.0.1 on 2026-02-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0010_person_residency_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="personidscan",
            name="scan_name",
            field=models.CharField(
                blank=True,
                help_text="Optional scan name (shown in UI)",
                max_length=50,
                null=True,
            ),
        ),
    ]
