# Generated by Django 6.0.1 on 2026-03-11 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
        ("persons", "0011_personidscan_scan_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company that inputted the person data",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="persons",
                to="companies.company",
            ),
        ),
    ]
