# Generated by Django 6.0.1 on 2026-03-11 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
        ("persons", "0012_person_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_column="company_id",
                help_text="Company that inputted the person data",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="persons_by_company",
                to="companies.company",
            ),
        ),
    ]
