# Generated by Django 6.0.1 on 2026-04-03 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportUnitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_unit_types",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport unit type",
                "verbose_name_plural": "Transport unit types",
                "db_table": "transport_unit_types",
                "ordering": ["company__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="TransportUnitModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(blank=True, max_length=30, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_unit_models",
                        to="companies.company",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="models",
                        to="transport.transportunittype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport unit model",
                "verbose_name_plural": "Transport unit models",
                "db_table": "transport_unit_models",
                "ordering": ["company__name", "type__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="TransportUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("identifier", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_units",
                        to="companies.company",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_units",
                        to="transport.transportunittype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport unit",
                "verbose_name_plural": "Transport units",
                "db_table": "transport_units",
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="transportunittype",
            constraint=models.UniqueConstraint(
                fields=("company", "name"),
                name="uniq_transport_unit_type_per_company_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="transportunittype",
            constraint=models.UniqueConstraint(
                fields=("company", "code"),
                name="uniq_transport_unit_type_per_company_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="transportunitmodel",
            constraint=models.UniqueConstraint(
                fields=("company", "type", "name"),
                name="uniq_transport_unit_model_per_company_type_name",
            ),
        ),
    ]
