# Generated by Django 6.0.1 on 2026-04-02 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransportUnitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Transport unit type",
                "verbose_name_plural": "Transport unit types",
                "db_table": "transport_unit_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TransportUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("identifier", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_units",
                        to="transport.transportunittype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport unit",
                "verbose_name_plural": "Transport units",
                "db_table": "transport_units",
                "ordering": ["name"],
            },
        ),
    ]
