# Generated by Django 6.0.1 on 2026-04-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportunit",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transport_units",
                to="transport.transportunitmodel",
            ),
        ),
        migrations.AddField(
            model_name="transportunit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="transportunit",
            name="name",
            field=models.CharField(max_length=10),
        ),
    ]
