# Generated by Django 6.0.1 on 2026-04-02 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportunit",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transport_units",
                to="companies.company",
            ),
        ),
    ]
