# Generated by Django 6.0.1 on 2026-04-03 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0002_transportunit_model_transportunit_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transportunit",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transport_units",
                to="transport.transportunitmodel",
            ),
        ),
    ]
