# Generated by Django 6.0.1 on 2026-04-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0003_alter_transportunit_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transportunit",
            name="type",
        ),
    ]
