# Generated by Django 6.0.1 on 2026-04-04 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_logo_company_name_short"),
        ("transport", "0004_remove_transportunit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportunit",
            name="technical_status",
            field=models.CharField(
                choices=[
                    ("ready", "Ready"),
                    ("reserve", "Reserve"),
                    ("out_of_service", "Out of service"),
                    ("maintenance", "Maintenance"),
                ],
                default="ready",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TransportOperationalParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=30)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("text", "Text"),
                            ("boolean", "Boolean"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Examples: L, kg, km, h, bar, %",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_operational_parameters",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport operational parameter",
                "verbose_name_plural": "Transport operational parameters",
                "db_table": "transport_operational_parameters",
                "ordering": ["company__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="TransportTechnicalParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=30)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("text", "Text"),
                            ("boolean", "Boolean"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Examples: L, kg, t, km, h, persons",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_technical_parameters",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport technical parameter",
                "verbose_name_plural": "Transport technical parameters",
                "db_table": "transport_technical_parameters",
                "ordering": ["company__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="TransportModelTechnicalParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("value_integer", models.IntegerField(blank=True, null=True)),
                (
                    "value_decimal",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("value_text", models.CharField(blank=True, max_length=255, null=True)),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_parameter_links",
                        to="transport.transportunitmodel",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model_links",
                        to="transport.transporttechnicalparameter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport model technical parameter",
                "verbose_name_plural": "Transport model technical parameters",
                "db_table": "transport_model_technical_parameters",
                "ordering": [
                    "model__type__name",
                    "model__name",
                    "display_order",
                    "parameter__name",
                ],
            },
        ),
        migrations.CreateModel(
            name="TransportModelOperationalParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_parameter_links",
                        to="transport.transportunitmodel",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model_links",
                        to="transport.transportoperationalparameter",
                    ),
                ),
                (
                    "max_technical_parameter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional technical parameter defining upper bound.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_max_links",
                        to="transport.transporttechnicalparameter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport model operational parameter",
                "verbose_name_plural": "Transport model operational parameters",
                "db_table": "transport_model_operational_parameters",
                "ordering": [
                    "model__type__name",
                    "model__name",
                    "display_order",
                    "parameter__name",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="transportoperationalparameter",
            constraint=models.UniqueConstraint(
                fields=("company", "name"),
                name="uniq_transport_operational_parameter_per_company_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="transportoperationalparameter",
            constraint=models.UniqueConstraint(
                fields=("company", "code"),
                name="uniq_transport_operational_parameter_per_company_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="transporttechnicalparameter",
            constraint=models.UniqueConstraint(
                fields=("company", "name"),
                name="uniq_transport_technical_parameter_per_company_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="transporttechnicalparameter",
            constraint=models.UniqueConstraint(
                fields=("company", "code"),
                name="uniq_transport_technical_parameter_per_company_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="transportmodeltechnicalparameter",
            constraint=models.UniqueConstraint(
                fields=("model", "parameter"),
                name="uniq_transport_model_technical_parameter",
            ),
        ),
        migrations.AddConstraint(
            model_name="transportmodeloperationalparameter",
            constraint=models.UniqueConstraint(
                fields=("model", "parameter"),
                name="uniq_transport_model_operational_parameter",
            ),
        ),
    ]
