# Generated by Django 6.0.1 on 2026-04-04 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0005_transportunit_technical_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportUnitOperationalValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_integer", models.IntegerField(blank=True, null=True)),
                (
                    "value_decimal",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("value_text", models.CharField(blank=True, max_length=255, null=True)),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_values",
                        to="transport.transportoperationalparameter",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_values",
                        to="transport.transportunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport unit operational value",
                "verbose_name_plural": "Transport unit operational values",
                "db_table": "transport_unit_operational_values",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("unit", "parameter"),
                        name="uniq_transport_unit_operational_value",
                    )
                ],
            },
        ),
    ]
